<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class GController extends Controller
{
    public $layout = '@app/views/layouts/global';

    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['entry'],
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function () { //have two params $rule , $action
                    $jumpUrl = Url::to(['/login/default/entry']);
                    $this->redirect($jumpUrl);
                },
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $actionId = Yii::$app->requestedAction->id;
        switch ($actionId){
            case 'add':
                $this->layout = '@app/views/layouts/form';
                break;
            case 'edit':
                $this->layout = '@app/views/layouts/form';
                break;
            case 'create':
                $this->layout = '@app/views/layouts/form';
                break;
            case 'update':
                $this->layout = '@app/views/layouts/form';
                break;
            case 'view':
                $this->layout = '@app/views/layouts/form';
                break;
            case 'index':
                $this->layout = '@app/views/layouts/list';
                break;
            case 'trash':
                $this->layout = '@app/views/layouts/list';
                break;
            default:
                $this->layout = '@app/views/layouts/global';
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function ajaxResponse($response = ['code'=>0, 'msg'=>'操作成功', 'data'=>[]])
    {
        header('Content-Type: application/json');
        exit(json_encode($response, JSON_UNESCAPED_UNICODE));
    }

}
