<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 2016/12/9
 * Time: 15:33
 */

namespace app\controllers;

use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class PController extends Controller
{
    public $layout = '@app/views/layouts/public';

    public function attachBehavior($name, $behavior)
    {
        return parent::attachBehavior($name, $behavior); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
//                'only' => ['logout','index'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['entry'],
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout','index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function () { //have two params $rule , $action
                    $jumpUrl = Url::to(['/login/default/entry']);
                    $this->redirect($jumpUrl);
                },
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
                /*'actions' => [
                    'index'  => ['get'],
                    'view'   => ['get'],
                    'create' => ['get', 'post'],
                    'update' => ['get', 'put', 'post'],
                    'delete' => ['post', 'delete'],
                ],*/
            ],
        ];
    }
}